coral-erm/coral

resources/admin/classes/common/DatabaseObject.php
resources/admin/classes/domain/Resource.php

implements fix from May 11, 2015 in usage module allowing for use of single database connection when generating related resource lists. There was an error for too many database connections if the parent and child resources numbered over 140.

Database connection error in Resources

---

resources/admin/classes/domain/ResourceStep.php
resources/admin/emails/DeletedPriorStep.txt
resources/admin/emails/ReassignedStep.txt
resources/ajax_forms/getResourceStepForm.php
resources/ajax_htmldata/getOutstandingQueue.php
resources/ajax_htmldata/getRoutingDetails.php
resources/ajax_processing/deleteResourceStep.php
resources/ajax_processing/updateResourceStep.php
resources/js/forms/resourceStepForm.js
resources/js/resource.js
resources/user.php

This PR is a copy of the https://github.com/ndlibersa/resources/pull/60
It adds a tiny patch to ensure translatability of a javascript string

resource Pr60, enhancements to the routing tab

---

licensing/user.php
management/user.php
organizations/user.php
resources/user.php
usage/user.php

Once it has been determined that a user needs to login before proceeding, stop executing PHP
code, in case the client does not respect Location headers by default (such as curl).
Resolves Issue #32 .
Applied to resources, licensing, organizations, management and usage modules.

Exit after redirecting to login screen

---

usage/install/install.php

Leaving out the $link param on line 145 makes the call fail, but the error message on
screen (from line 147) shows a blank MySQL message, since there was no error with the
$link itself.
Without this change, installing the usage module fails in PHP 5.5.9.

fix syntax error in mysqli_select_db in usage/install/install.php

---

licensing/admin/classes/domain/Expression.php

MySQL appears to be case insensitive, so capitalization doesn't matter in this case. BUT this is not true of every database platforms, so if we hope to support other platforms someday, this case needs to be fixed. Also, inconsistent capitalization makes the code confusing and may lead to bugs.

Licensing: Fix capitalization problem

---

resources/install/install.php

When I try to install this module, I am getting the error "Fatal error: Call to undefined function mysql_query() in /var/www/html/resources/install/install.php on line 64"
I suspect this was broken by 26ae17c which changes a lot of mysql_query calls, and also the commit message says "not yet tested"

Correct broken mysql_query (Pr/71 on old resources module)

---

resources/install/protected/update_NEXT.sql

This commit removes SQL from the upgrade script that creates an already existing table (after also dropping it, which would lose existing data). Those lines were probably included accidentally.

Remove extraneous SQL from update script

---

management/index.php

For some reason the php 5.6 parser was fine with this.
But the PHP 7 parse was throwing a parse error

add missing closing php tag

---

management/ajax_forms.php

Before, the error message was in the HTML code but not visible.
Now:

management: new doc form: fix unclosed <select> that broke error message

---

resources/admin/classes/domain/Resource.php

I got an `Undefined offset: 0`  when it was doing the `$match[0];` on the result.
After having thought that it could be a problem it turns out to be just the [last line of $conditional_joins](https://github.com/tuxayo/Coral/blob/d10e038a02057b6076fa084aaa2dd8126398afd6/resources/admin/classes/domain/Resource.php#L1290) that was causing the last element to be `""`
Nothing really problematic beside the Notice, so while I'm at it, here is a fix.

resources: fix undefined offset: don't try to regex an empty string

---

resources/ajax_processing/submitNewResource.php

Ressource::setIsbnOrIssn expects an array and sending a ' ' was making the
foreach unhappy.
https://github.com/Coral-erm/Coral/blob/9398f2d413be7dea644a1e59eabd0bba6d4dc8f4/resources/admin/classes/domain/Resource.php#L2457
https://github.com/Coral-erm/Coral/blob/90af125b8aa56645496caddef0f65161f34268a6/resources/import.php#L395
https://github.com/Coral-erm/Coral/blob/82e99ed032cb7b5066d04040238d611cae1275ea/resources/ajax_processing/submitProductUpdate.php#L18

resources: fix isbnOrISSN that was assigned '' instead of []

---

resources/ajax_processing/checkUploadAttachment.php

It's a syntax error for the PHP 7 parser (but not for the 5.6 one...)
It came from there:
https://github.com/Coral-erm/Coral/commit/137c9fd3fa3ce1e348fe1551dca8ef4662ced8be#diff-72bd8d1f368642e7efcbee7099f52c26L671
But when it was extracted to the current file it should have been
replaced by a return to prevent the rest from executing.

fix break that should have been converted to a return

---

resources/templates/header.php

It was 'newLicense' instead of 'newResource'.
It doesn't seem to be used anywhere:
- after searching 'newLicense' in the code.
- after checking in the browser the JS callbacks on the link.
So no regression is expected.
Clicking on it and creating a resource still works.

Resources: fix new resource link id

---

resources/install/CORALInstaller.php

Invoking session_start() inside class CORALInstaller triggers an syntax error with an unexpected T_STRING. I'm moving it back up to the beginning of the file where Usage's CORALInstaller.php has it. 
Does any one know a reason why we shouldn't do this?

Move session_start() out of class definition

---

resources/admin/classes/common/Email.php
resources/admin/configuration_sample.ini

This patch allows the Email class to try to find a correct from for sending emails, in this order:
- Is there a emailFrom field in the config file?
- Is $_SERVER['SERVER_NAME'] defined?
- Is $_SERVER['HTTP_HOST'] defined?
- use system hostname

Issue#123: From Email is incorrect

---

resources/ajax_processing/submitAcquisitions.php

The acquisition currentStartDate and currentEndDate were being passed `'null'` which mysql normally rejects as incorrect SQL for a `DATE` field. All the other `NULL` values being passed into the update query were coming in correctly as `NULL`, so I changed this file to match which fixed our database error.

Fixing poorly formatted NULL acquisitions dates

---

resources/admin/classes/common/Utility.php

I repeatedly got the error "Notice: Undefined index: HTTPS in C:\xampp\htdocs\coral\resources\admin\classes\common\Utility.php".  
I should note that regardless of what I use for the URL's prefix (www, http:, https, etc), it always removes it.  so **www.mycoral.com** becomes **mycoral.com**.

Ridding "Notice: Undefined index:"

---

resources/admin/classes/domain/Resource.php

This patch fixes resource list for MySQL 5.7.
See http://stackoverflow.com/questions/34115174/i-am-getting-an-error-in-mysql-related-to-only-full-group-by-when-executing-a-qu for reference.
Fixes issue #105

Issue 105: Resource list not showing up with MySQL 5.7

---

auth/install/create_tables_data.sql
licensing/install/protected/install.sql
management/install/protected/install.sql
resources/install/protected/install.sql

An install was successfully done (except for module Reports #110 ) on MySQL 5.7, PHP 7, Ubuntu 16.04.
And a resource was created.
Fixes #50

Fix default timestamps to be compatible with MySQL 5.7 - issue #50

---

organizations/install/organizations.php

Added the missing install dependency have_read_write_access_to_config to fix the bug where the organizations module did not get its configuration file written when installing 2.0 from scratch.

Organizations install patch

---

resources/ajax_forms/getUpdateProductForm.php
resources/js/forms/resourceUpdateForm.js

Resolves #148 
This is a quick fix to resolve the bug.
A more thorough refactor of the javascript and HTML is needed, since it seems to be halfway between an original, single parent version, and the current multiple add version. 
This makes it difficult to debug, and performance could be improved with more precise jQuery selectors and HTML dedicated to adding multiple parents in one edit.

Fix duplicate Parent bug in updateProduct

---

licensing/admin/classes/common/Utility.php

If there's no http / https prefix, the isset() keeps a warning from being thrown.
Previously #161 on master branch, reopening on new development branch.

Removes "Undefinied index.." if no prefix

---

resources/css/style.css

Fixed #179. a.showIssues and a.showAccounts were missing the relevant CSS to capitalize the first letter found in the other .show* classes

Fixed #179

---

resources/ajax_htmldata/getRightPanel.php

The newest version of the reports module added parameters to the database in a way that should prevent the changing form parameters that caused this button to break in the past.  prm_3 is now the title search parameter.

Fix "Get Statistics" button

---

resources/ajax_htmldata/getProductDetails.php

Workaround that resolves #178. Set the max-width property of the URL <td> and set the style of the table to break word on word-wrap. The URL overflows outside of the <td> element if word-wrap: break-word isn't set.
A more ideal solution would likely require significant changes to styling. With the table layout, heavy in-line styling usage, explicit widths (especially when child elements had larger widths than their parent), and CSS styles marked !important, it was difficult to find the root cause and provide an alternate solution to the issue.
We tried collapsing the helpful links box and displaying it when the user hovers over it, but it still covered content and buttons when the content made the table exceed a certain width (despite having a width explicitly set in in-line styling of …

Iss178 workaround

---

tests/_data/test_database.sql

This resolves the following issues that I experienced:
> $ mysql < tests/_data/test_database.sql
ERROR 1100 (HY000) at line 712: Table ‘document’ was not locked with LOCK TABLES
> $ mysql < tests/_data/test_database.sql
ERROR 1100 (HY000) at line 929: Table ‘license’ was not locked with LOCK TABLES

Issue #276: table names needed capitalizing in test_database.sql file.

---

auth/admin/classes/common/Utility.php

Related to #77.
PHP Notice: Undefined index: HTTPS in ./auth/admin/classes/common/Utility.php on line 71
Visit a CORAL instance, like http://coral/auth/, on a non-SSL server.

Issue #77: Undefined index: auth/…/Utility.php Line 71

---

resources/admin.php
resources/admin/classes/domain/Downtime.php
resources/admin/classes/domain/Resource.php
resources/ajax_forms/getNewDowntimeForm.php
resources/ajax_forms/getUpdateProductForm.php
resources/index.php
resources/queue.php
resources/resource.php

Mostly using `isset()`. All original notices are included in the commit messages.
Issue #77

Add checks to avoid PHP Notices in Resources code.

---

resources/admin/classes/common/Html.php
resources/index.php

Addresses #340.
I changed all the instances of this issue rather than just the ones in the deprecated notices.

Issue #340: fix statically called non-static methods in Html class.

---

resources/install/protected/2.1.0/001-318.sql

Addresses #318. Merge and release strategy for `*.sql` files still to be worked out (see #302).
Run a `mysql` command similar to the following to apply the change.
```
mysql coral_resources < resources/install/protected/2.1.0/001-318.sql 
```
After running, check that the data type for the `configuration` column in the `ImportConfig` table is now `TEXT`.

Issue #318: Modify `configuration` column type of `ImportConfig` table.

---

resources/api/index.php

This PR allows #344 to work with #244 .
More specifically, a default order needs to be created when submitting a resource through the API, in order to be able to attach the acquisition type to it.

Fix API for multiple orders on resource creation

---

auth/admin/classes/common/Configuration.php
licensing/admin/classes/common/Configuration.php
management/admin/classes/common/Configuration.php
organizations/admin/classes/common/Configuration.php
resources/admin/classes/common/Configuration.php
usage/admin/classes/common/Configuration.php

Addresses #326.
Enable PHP error reporting for E_DEPRECATED and load any CORAL page besides the root index and there will be Deprecated messages. Apply this fix and Deprecated messages for this issue are no longer there.

Issue #326: Fix statically called non-static method.

---

organizations/admin/classes/common/Utility.php
resources/admin/classes/common/Utility.php
resources/admin/classes/domain/Resource.php
resources/api/index.php
resources/api_client/index.php
resources/api_client/local.css

- adds a fund code drop down to the api_client form
- adds css styles and reworks the form to better use html form standards and the pure-css css framework
- imports some styles from main CORAL pages
- adds in optional commented-out-fields for author and isbn/issn inputs to be added to the description text field
- adds in API flight routes for getting funds for the dropdown
- checks a number of variables for isset or !empty before calling them
- adds in an urgent checkbox for rush orders with a browser native datepicker if the user checks it
- subjective change to make the administering site input (labeled 'Library) to be a single dropdown instead of a multi-select box.

NCSU API_Client fundcode dropdown and general form style enhancements

---

auth/admin/classes/common/DBService.php
auth/admin/classes/common/DatabaseObject.php
licensing/admin/classes/common/DBService.php
licensing/admin/classes/common/DatabaseObject.php
licensing/admin/classes/common/Utility.php
management/admin/classes/common/DBService.php
management/admin/classes/common/DatabaseObject.php
management/admin/classes/common/Utility.php
organizations/admin/classes/common/DBService.php
organizations/admin/classes/common/DatabaseObject.php
reports/admin/classes/common/DBService.php
reports/admin/classes/domain/ParameterFactory.php
reports/admin/classes/report/Report.php
reports/index.php
usage/admin/classes/common/DBService.php
usage/admin/classes/common/DatabaseObject.php
usage/admin/classes/domain/Platform.php

As pointed out in #245 , the patch recently merged in development as part of #292 only addressed the problem for the resource module.
This PR extends the use of a single DB connection to all modules.

Issue 145 [Follow-up]: Use singleton for database connection

---

resources/api_client/index.php

probably not needed, but here's a testplan.
without this PR:
1. submit a new resource with the api_form, but don't fill in the neededBy date input. (it should be hidden unless you check the 'urgent' checkbox.)
2. look at the new resource record and you'll see an initial note with a neededBy date of 12/31/1969 or 01/01/1970.
with this PR:
2. you should not see a neededBy date at all in the initial note section.

fixes #361

---

organizations/index.php

Addresses #355.
Add isset() to fix PHP Notice: Undefined index: org_orderBy
in …/organizations/index.php on line 153
Add isset() to fix PHP Notice: Undefined index: org_numberOfRecords
in …/organizations/index.php on line 149
Add isset() to fix PHP Notice: Undefined index: org_pageStart
in …/organizations/index.php on line 145
Add isset() to fix PHP Notice: Undefined index: org_startWith
in …/organizations/index.php on line 140
Add isset() to fix PHP Notice: Undefined index: org_contactName
in …/organizations/index.php on line 95
Add isset() to fix PHP Notice: Undefined index: org_contactName
in …/organizations/index.php on line 94
Add isset() to fix PHP Notice: Undefined index: org_organizationRoleID
in …/organizations/index.php on line 78
Add isset() to fix PHP Notice: Undefined index: …

Issue #355: fix PHP Notices on Organizations index page.

---

resources/admin/classes/domain/Resource.php
resources/admin/classes/domain/ResourceAcquisition.php
resources/ajax_htmldata/getAcquisitionsDetails.php
resources/ajax_htmldata/getContactDetails.php
resources/ajax_processing/submitNewResource.php
resources/js/resource.js
resources/resources/cataloging.php

Since contacts are now linked to orders, orders are to be deleted when a resource is deleted (note: I have the feeling that this was already done before, but it may have been lost in a merge / rebase).
Also fixes #348

Remove orders on resource deletion

---

resources/ajax_htmldata/getEbscoKbTitleDetails.php
resources/ajax_htmldata/getSearchEbscoKb.php
resources/templates/ebscoKbPackageList.php
resources/templates/ebscoKbTitleList.php

PR #334 introduced EBSCO KB integration.
However, a lot of strings brought by this development do not use gettext and are therefore not translatable.
This PR fixes this.
Please note that a few strings are still not translatable, but this requires further investigation on how to make them translatable, and this is beyond the scope of this PR (titleSearchFieldOptions, titleResourceTypeOptions, selectionOptions, and packageContentTypeOptions in admin/classes/domain/EbscoKbService.php )

Make Ebsco KB integration translatable

---

resources/admin/classes/common/Dashboard.php

Dashboards (#314) are currently broken, since the merge of multiple ordering (#244). This PR fixes the SQL queries to be compatible with multiple ordering.
Test plan:
- Add acquisitions to some resources
- Check that the dashboards are not displayed, with SQL errors in the logs
- Apply the patch
- Check that the dashboards are now correctly displayed.

Fix dashboards for multiple ordering

---

resources/ajax_forms/getEbscoKbPackageImportForm.php
resources/ajax_processing/importFromEbscoKb.php

__Prerequisite__ have Ebsco API credentials so you can query EBSCO KB.
1. In the EBSCO KB search, find a package with over 10,000 records (Academic Search Complete is a good example). Click __Import__. You should have red warning under Package Titles.
2. Find a package with over 10,000 records and your library has < 10,000 records. The easiest way is to do a package search with Selection set to 'Not Selected'. Click __Import__. The same warning should appear beneath 'All Titles'. But Selected Titles and Package Only should still be an option.
Finally, if you want to edit the wording, it's at the top of the file in the `$ebsco10kLimitText` var

EBSCO Kb Integration: Warning about 10k records

---

resources/js/plugins/thickbox.js

Thickbox, which we use in Coral, and most of modal popup libraries, allow to close a modal popup with the escape key.
However, there is a bug in our modified version of thickbox that prevents this behaviour.
Test plan:
Before the fix: open a modal popup (new resource for example). You can't close the popup with the escape key.
After the fix: open a modal popup (new resource for example). You can close the popup with the escape key.

Allow to close a modal popup with the escape key

---

resources/admin/classes/domain/Resource.php
resources/ajax_processing/deleteResource.php

Fixes #93 
Add php response code and resource not found error message
1. Create a resource
2. Get the resource id
3. Ping the delete resource url: some-domain/resources/ajax_processing.php?action=deleteResource&resourceID=`resourceID`
4. Should receive a `Resource successfully deleted` message and 200 response code
5. Ping the same url
6. Should receive a `Resource not found. Error: <db error message>` and 404 response code

Error 404 when trying to delete non-existent resource

---

organizations/ajax_htmldata.php
organizations/summary.php

Fixes #94 
Instead of searching for a missing `http` string, instead search for a missing protocol `://`
Additionally, added CSS to allow urls to wrap. Very long urls would bleed over to the helpful links section
In the organizations module, add an ftp url as the company url or the login url (login url under Accounts).

Issue 94: Allow ftp:// organization urls

---

organizations/admin/classes/domain/Organization.php

PHP message: PHP Fatal error:  Uncaught Exception: There was a problem with the database: Expression #5 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'coral_organizations.OHP.parentOrganizationID’ which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by in /var/www/coral/organizations/admin/classes/common/DBService.php:39
Stack trace:
#0 /var/www/coral/organizations/admin/classes/common/DBService.php(71): DBService->checkForError()
#1 /var/www/coral/organizations/admin/classes/domain/Organization.php(550): DBService->processQuery('SELECT O.organi…', 'assoc’)
#2 /var/www/coral/organizations/ajax_htmldata.php(895): Organization->search(Array, ‘TRIM(LEADING ‘T…’, ‘’)
#3 {main}
thrown in …

Add item to GROUP BY for new MySQL 5.7 default compatibility.

---

LangCodes.php
auth/admin.php
auth/index.php
index.php
licensing/templates/header.php
management/templates/header.php
organizations/templates/header.php
reports/index.php
resources/templates/header.php
usage/templates/header.php

PR Not found :)
Fixes issues #103 and #403 
Test plan:
- Clear your Coral language cookie
- Without changing language (no cookie set), check that the browser's language is selected by default in language dropdown lists everywhere in Coral.
- Change the language (language cookie is set), check that the language you chose is selected in language dropdown lists everywhere in Coral.

Issues 103, 403: Fix selected language in dropdown when language cookie is not set.

---

resources/import.php

Issue 347: Add an error message on the import tool page when mbstring is missing

---

usage/admin/classes/common/Utility.php
usage/uploadComplete.php

The hidden form at the bottom of [uploadConfirmation.php](https://github.com/coral-erm/coral/blob/development/usage/uploadConfirmation.php#L342) does not contain a `startDate` & `numMonths` value when manually importing stats file. This caused the scripts in [uploadComplete.php](https://github.com/coral-erm/coral/blob/development/usage/uploadComplete.php#L38)(line 38-55) to incorrectly set the `$multYear` var to true.
To avoid any unnecessary meddling in how uploadConfirmation.php generates its variables, I decided to add additional logic to check for the existence of the `startDate`. As I understand it, there is a feature request to allow manual multi-year imports, at which point the logic for finding the start/end dates of an import file can be added. But this patch works until that …

SirsiDynix Issues: Manual Stats Imports failing

---

install/providers/have_database_access.php
install/providers/have_default_db_user.php
organizations/install/protected/install.sql
resources/install/protected/install.sql

This is supposed to fix the empty `$db_info` during the install process which resulted in error messages about '... denied from @ '  as reported #332 
It also attempts to improve the language used when asking for the user with database creation permissions to be more clear about what to expect. 
You can verify this by installing CORAL using a database user without permission to modify or create other users, so when it tries to create `coral_user` it will fail (silently, by the way, which is another issue I'll open shortly) and thus when it tries to use `coral_user` at the end of the process to actually run CORAL commands, you'll get 
without this patch, and this 
with the patch. 
There is also an installation SQL issue error that I'm seeing
`Duplicate column name 'ebscoKbID'
For …

#332 installer bug fix 

---

resources/admin/classes/domain/Resource.php
resources/ajax_forms/getNewResourceForm.php
resources/ajax_processing/submitNewResource.php

- Don't create multiple orders when a resource is saved as draft before being submitted
Test plan:
- Before the fix: Create a resource. Save it as draft, validate the resource. Two default orders will be created instead of one. If you edit the resource as draft multiple times before validating it, multiple default orders will be created.
- After the fix: Proceed as before. Check that only one default order has been created when the resource is validated.
- Fix acquisitionType selection when editing a resource saved as draft
Test plan: 
- Before the fix: Create a resource with an acquisitionType. Save it as draft. Edit it as draft. The acquisitionType will not be selected in the form.
- After the fix: Proceed as before. Check that the acquisitionType is selected when editing the resource …

Fix multiple issues with resource submission

---

organizations/admin/classes/common/DatabaseObject.php

This is necessary when the Organization module is configured to use the Resource module's Issue functionality.

Restore ability for org Issue class to represent resource module Issue table

---

organizations/admin/classes/api_client/INSTALL
organizations/admin/classes/api_client/KohaClient.php
organizations/admin/classes/api_client/OAuth.php
organizations/admin/configuration_sample.ini

PR #296 introduced vendors synchronization with an ILS.
This PR adds OAuth support to authenticate against the ILS API.
See:
https://oauth.net/
http://oauth2-client.thephpleague.com/

Allow to use OAuth for the ILS connector

---

licensing/admin/classes/domain/License.php
resources/admin/classes/domain/Resource.php
resources/api/index.php

The following route is currently broken on devel:
`resources/api/resources/@id/licenses`
> 500 Internal Server Error
> Invalid argument supplied for foreach() (2)
> #0 /home/coral/www/resources/api/index.php(327): flight\Engine->handleError(2, 'Invalid argumen...', '/home/coral/www...', 327, Array)
This PR fixes it.
It also enhance some existing routes:
- Aliases are now embedded in `resources/api/resources/@id/` response.
- Qualifiers are now embedded in `resources/api/resources/@id/licenses` response.
It also introduce a new route:
`resources/api/resources/@id/packages` to get the parent resources of a given resource.

API: Fix licenses route

---

templates/footer.php

Before we publish the release we need to update the footer. We didn't merge #406 yet (we should!), so this is just slightly modifying the existing footer.

Update version in footer for 3.0.0 beta release

---

resources/admin/classes/domain/Fund.php
resources/js/resource.js

Fix blank panes in Resource detail page found with Firefox (version 38.3 though very old)
Fix blank fund list  or newly added missing in fund list in Edit Cost From, for the Fund class' method  getUnArchivedFunds can only handle NULL value but not "0" of the archived field of the Fund table.

Blank form in Resource Module and Fund List Dropdown not populating

---

resources/ajax_htmldata/getDashboard.php
resources/ajax_htmldata/getDashboardYearlyCosts.php
resources/dashboard.php
resources/dashboard_yearly_costs.php

The left panel is not visible in dashboards when there are too many results, because it is vertically centered. This patch aligns it vertically with the results table.
Before:
After:

Dashboards: align left panel and results table vertically

---

auth/admin.php
auth/index.php
index.php
licensing/templates/header.php
management/templates/header.php
organizations/templates/header.php
reports/index.php
resources/templates/header.php
usage/templates/header.php

When running Coral on a non-standard port, for example :9090,
switching the language from English to another is not possible.
When choosing another language from the pull down, the page
reloads and jumps back to English instead of the language chosen.
This is because the lang cookie storing the selected language isn't set.
After some research the problem is that Coral tries to set the
domain attribute of the cookie to the host including the port
number. Instead it should be using the host name without the port.
Cookies do not provide isolation by port. If a cookie is readable
by a service running on one port, the cookie is also readable
by a service running on another port of the same server...
(https://tools.ietf.org/html/rfc6265#section-5.1.3)
Test plan:
- Configure Coral to run on …

(issue #448) Can't switch language if Coral runs on a non-standard port

---

templates/footer.php

This is just to remove the Beta label from the 3.0.0 footer before release.

3.0.0 footer update

---

resources/admin/classes/domain/AccessMethod.php

Test plan:
1) On master or development branch, try to delete an unused access method in admin. The access method cannot be deleted.
2) Apply the PR
3) Try to delete an unused access method in admin. The unused access method can be deleted. Check that a used access method cannot be deleted.

Fix access method deletion in admin

---

resources/admin/classes/domain/User.php

- Use unicode string comparison for privileges check

Fix resources menu display for turkish translation

---

resources/admin/classes/domain/AlertDaysInAdvance.php

Fix for issue #446 : Missing Field in coral_resources.Resources
Test plan:
* Add an email in admin -> Alert Settings
* set an end date for an order that matches a "Days in advance of expiration" in admin -> Alert Settings.
* call the sendAlerts script: `wget -O - http://coral.local/resources/sendAlerts.php`
* Check that you received an alert email.

Issue 446: Fix end date alert

---

organizations/admin/classes/api_client/KohaClient.php
organizations/admin/classes/api_client/OAuth.php
organizations/admin/interfaces/ILSClient.php
organizations/ajax_processing.php
organizations/js/forms/organizationSubmitForm.js
resources/api_client/composer.json

This patch provides a bugfix and several enhancements for OAuth authentication in the Koha connector:
- Fix incorrect use of "Authorization" header.
- Add better error handling
- Authentication token is now stored in session and re-used until expired.
- Replace incorrect call to Koha API.
Test plan:
Koha version >= 18.05 needed.
- Coral: Install Unirest and league/oauth2-client in resources/api_client (composer might be the easiest way to do it)
- Koha: Install Net::OAuth2::AuthorizationServer and enable RESTOAuth2ClientCredentials syspref.
- Koha: Create a user for the REST API, edit this user, click on more -> manage API Keys -> Generate new client id/secret pair
- Coral: edit organizations/admin/configuration.ini as such:
```
[ils]
ilsConnector=koha
ilsVendorRole="Vendor" …
```

OAuth authentication: bugfix and enhancements

---

licensing/admin/classes/domain/License.php

Updates the query in the getResourceArray method in the License class to join through the ResourceAcquisition table.
Resolves #486

Licensing: Restore Resource Linking in the Helpful Links sidebar

---

resources/css/style.css
resources/import.php

This patch allows to save an import configuration on the import page, allowing to create/edit configurations during the import process.
Also, bug fix: currency, orderType and sendemails attributes were not properly
transmitted through import process
Test plans:
Create a new config:
- Start an import
- Create a configuration
- Save current configuration
- Check in admin -> Import Configuration that the configuration has been added
Edit an existing configuration and save it as new:
- Start an import
- Load an existing configuration
- Edit it
- Save it with a new name
- Check in admin -> Import Configuration that the configuration has been added

Add an option to save import configuration on the fly

---

resources/admin/classes/domain/Resource.php
resources/admin/classes/domain/ResourceAcquisition.php
resources/css/style.css
resources/resource.php

- Sort orders by subscription start date desc, subscription end date desc
- Select the first order that is currently active (start date <= today => end date)
- Show the order's organization after the dates
Before:
After:

Improvements to the order dropdown list

---

resources/import.php

- acquisition type is displayed in mappings
- acquisition type is attached to the default order
- make coral field names and other strings translatable

Issue 493: Fix acquisition Type in import

---

resources/import.php

Check that the $verb variable and the sentences it is used in can correctly be extracted by gettext.
See https://github.com/coral-erm/coral/pull/507#pullrequestreview-172217651

Fix import page translation

---

resources/admin/classes/domain/ResourceAcquisition.php
resources/ajax_processing/submitAcquisitions.php
resources/install/protected/3.0.1/001-478.sql
resources/resource.php

Fix for #478 
Test plan:
- apply resources/install/protected/3.0.1/001-478.sql
- Check that you can unset an order subscription start date
- Check that you can unset an order subscription end date
- Check that you can unset both
- Check that the display is correct in the order dropdown list
- Check that the active order is correctly selected
When both dates are unset, the order id is displayed, so the user can differentiate the orders.

Issue 478: Allow subscription start and end date to be null

---

common/common_directory.php
common/configuration_sample.ini
resources/admin/classes/domain/Resource.php

Currently, Coral's date format is hardcoded in common/common_directory.php
This patch allows to specify the date format in common/configuration.ini, with a fallback to the default date format if nothing is specified.
```
[settings]
date_format = "%m/%d/%Y"
```

Allow to specify date format in common/configuration.ini

---

licensing/js/common.js
licensing/templates/header.php
management/js/common.js
management/templates/header.php
organizations/js/common.js
organizations/templates/header.php
resources/js/common.js
resources/js/forms/costForm.js
resources/templates/header.php

Improvement/fix for #520 : Date.format (used by datepickers) is now configurable in a single file (`js/common.js` ) (instead of having to configure it in every module)

Issue 520: Allow to modify Date.format in the main common.js file

---

resources/admin/classes/domain/Resource.php

Fix for Issue #527 
Too many results were returned when searching on both note type and note text.
Test plan:
1) Apply the patch
2) Search resources using note type and note text
3) Check that the results are resources having a note of the searched type containing the searched text (and not a mix of both).

Issue 527: Fix resource search on note type and note text.

---

templates/footer.php

The footer needs to reflect the releasing version. I'll wait to merge this until right before merging development into master, and then make another pull request to set it back to DEVLOPMENT right after so people pulling the Development branch don't have the wrong footer for long.

Update footer in preparation for release.

---

common/common_directory.php
js/common.js
licensing/templates/header.php
management/templates/header.php
organizations/templates/header.php
reports/templates/header.php
resources/templates/header.php
usage/templates/header.php

Background: Issue #581 : We shouldn't have to patch Coral to specify a date format for the datepickers (see PR #523) but rather be able to specify it in the main configuration file.
Datepickers date format can be specified in common/configuration.ini, as such:
```
[settings]
datepicker_date_format = "dd/mm/yyyy";
```
If datepicker_date_format is omitted, it will be defaulted to 'mm/dd/yyyy'

Issue 581: Specify datepickers date format in common/configuration.ini

---

organizations/admin/classes/api_client/OAuth.php

Background: Issue #578 
Issuing a refresh token is optional at the discretion of the authorization server.
This patch allows Coral to ask for a brand new token if the OAuth server doesn't
provide a refresh token, instead of silently failing to authenticate.

Issue 578, OAuth: Get a brand new token if the server doesn't provide a refresh token

---

usage/admin/classes/domain/SushiService.php

Removes name spaces from SUSHI responses. This the same fix but different code as PR #579.
This was previously a PR to coral:master, which was incorrect. I've correctly made this a PR to coral:development.

Sirsi sushi issues

---

common/common_directory.php
common/configuration_sample.ini
licensing/ajax_processing.php
management/ajax_processing.php
organizations/ajax_processing.php
organizations/templates/header.php
resources/admin/classes/domain/Resource.php
resources/ajax_processing/insertDowntime.php
resources/ajax_processing/submitAcquisitions.php
resources/ajax_processing/submitCost.php
resources/ajax_processing/updateDowntime.php

This is an extension of #581 and #582 
Prior to this fix, dates within a form are formatted by the datepicker plugin. Thus, in the config file, if the format were `dd/mm/yyyy`, the date __January 2nd, 2019__ would be formatted _and submitted_ as the string `02/01/2019`.
But the php scripts that parse the `$_POST` variables are using [`strtotime()`](https://www.php.net/manual/en/function.strtotime.php), which "..expects to be given a string containing an English date format". Further digging into php docs showed that strtotime [only works with American date formatting](https://www.php.net/manual/en/datetime.formats.date.php) when using forward slashes, and has very specific formats for dashes.
Thus the above string of `02/01/2019` will always be parsed as __February 1st, 2019__ using …

SirsiDynix: Additional Datepicker fixes

---

common/common_directory.php
common/configuration_sample.ini
licensing/templates/header.php
management/templates/header.php
organizations/templates/header.php
resources/templates/header.php
usage/templates/header.php

Background: issue #365 : Switching module should not open an new windows
In common/configuration.ini:
```
[settings]
open_new_windows = Y/N
```
By default, the links are opened in a new window/tab.

Issue 365: Opening modules in the same or a new window is configurable.

---

resources/admin/classes/domain/Resource.php
resources/index.php

Background: see issue #623 
Currently, resources can be filtered with the following relationship criteria:
- **All**: all resources are displayed (child, parent, or no relationship)
- **Parent**: only parent resources are displayed
- **Child**: only child resources are displayed
This patch adds the following criteria:
- **None**: only resources that are neither parent nor child are displayed
(ie: only resources with no relationship)
Test plan:
- Perform a search on the resources index page, with 'None' in the Relationship
dropdown list.
- Check that only the resources with no relationship are displayed.

Issue 623: Search resources with no relationship

---

licensing/calendar.php

The calendar page in the licensing module is currently broken: it never returns any data.
This patch intends to fix this.
Please note that this is a hotfix. It does return some data now, but I didn't check that said data is what is expected.
Please test this, and report any functional problem.

Fix licensing calendar

---

resources/dashboard_yearly_costs_exports.php

Background: Issue #636  
Test plan:
- Check that the "All detail costs" column is currently missing from yearly
costs CSV exports (although displayed in the yearly costs page)
- Apply the patch
- Check that the column is now in the CSV exports and the values are correct.

Issue 636: Add missing "All detail costs" column in yearly costs dashboards exports

---

reports/admin/classes/common/Base_Object.php
reports/admin/classes/common/Configuration.php
reports/admin/classes/common/DynamicObject.php
reports/admin/classes/common/NamedArguments.php
reports/admin/classes/common/Utility.php

The reports module is currently broken:
PHP Fatal error:  Uncaught Error: Class 'Configuration' not found in /home/coral/www/common/common_directory.php:78
This patch adds the common classes also used by the other modules and fixes the problem.
This patch should be merged before release.

Add common classes to the reports module

---

resources/admin/classes/common/Dashboard.php

Background: issue #638 
Test plan:
- Find a resource with several subjects attached.
- Check that the 'All cost details' value is wrongly
multiplied by the number of attached subjects.
- Apply the patch.
- Check that the 'All cost details' value is now correct.

Issue 638: Fix yearly costs dashboards sums for resources with multiple subjects

---

templates/footer.php

Changing the footer in preparation for 2020.02 release. We need to change it back to DEVELOPMENT after the release is merged into the master branch.

Change the footer for 2020.02

---

resources/import.php

Customer reports that when using the Resources module import utility, the system creates note fields for every column you specify in the import configuration, for each imported resource, even if there is no data in the relevant cell.
Moreover, the note appears with the date created, followed by the word "by" and then a blank empty space. It appears that the Created By field of the note is not given the username of the user running the import, as expected.

Blank note fields created by resources/import.php

---

licensing/ajax_htmldata.php

A SirsiDynix customer reported that it is not possible to view the license expression qualifiers on the Expressions tab of the license record if the user has the "view only" privilege. This seems unintentional since the same user can view the qualifier on the Expression Comparison page. Moreover the tool tip for the user admin states "View only users can view all license information, including the license pdf."
This change adds the qualifier to the Expressions tab for users with the "view only" privilege. The option to edit or remove the expression does not appear.

Add qualifiers to license Expressions tab for "view only" user

---

licensing/ajax_htmldata.php

This PR removes the paperclip icon and restores the 'view document' text for the first document entry in a License's Document list.
Opened on behalf of @ehartnett

Revert paperclip icon to view document in licensing/document view

---

organizations/ajax_processing.php
organizations/css/style.css
organizations/templates/header.php
resources/admin/classes/domain/Organization.php
resources/admin/classes/domain/Resource.php
resources/ajax_processing/insertDowntime.php
resources/ajax_processing/updateDowntime.php
resources/css/style.css

These changes address several issues with downtime logging:
- When entering downtime, all dates were incorrectly recorded as being in 1969. This was caused by a fix to allow configuration of date format used for the date picker tool. 
- Unable to enter downtime in the Organizations module (due to a typo on startDate).
- Unable to export downtime from the Resources module.
I've also made some very minor style changes to make it easier to see where one downtime definition ends and the next one starts in cases where there are several listed.

Fix to downtime logging feature

---

usage/uploadComplete.php

This fix addresses an issue whereby clicking "view archive" in the import log after using the File Import tool gives a 404 error. File is now copied from counterstore to archive folder and filename is appended with timestamp and ".txt" suffix.

ERM-93 Fix to view archive for file import

---

licensing/ajax_processing.php
management/ajax_processing.php

On licensing upload form, if no effective date is entered, this induce a msql error
similar problem on management module

string 'null' sent instead of null value caused data saving failure

---

organizations/js/orgDetail.js
resources/js/resource.js
usage/ajax_htmldata.php
usage/js/forms/platformNoteSubmitForm.js
usage/js/forms/publisherNoteSubmitForm.js

Fixed logins tab loading issue in usage module

---

usage/admin/classes/common/Utility.php

SUSHI statistics can be retreived from a stored URL, but those are downloaded locally before being processed by the uploadComplete.php script. Because of that, we can simply refuse to load data from URLs using the (local) utf8_fopen_read function, which is only used to load server-local files into memory for processing.

Do not process URLs passed directly from users

---

js/plugins/jquery.datePicker-patched-for-i18n.js
resources/resource.php

This PR:
- Resolves #747 
- Removes redundant loading of javascripts from resource.php that have already been loaded in [header.php](https://github.com/coral-erm/coral/blob/ERM-63-modern-jquery-update-with-php8/resources/templates/header.php#L54)
- Restores the i18n keys to the datepicker plugin
- Updates the datepicker plugin to use the latest version from the original author: http://2008.kelvinluck.com/assets/jquery/datePicker/v2/demo/scripts/jquery.datePicker.js
- Attempts some code formatting cleanup
The latest, original version of the plugin appears to include all the modern jquery updates that were provided by the forked version along with additional improvements and fixes. I haven't found any issues testing these changes locally.

[747] Updates for jquery datepicker plugin and javascript includes cleanup

---

management/js/common.js

In the management module, the datepickers were being initialized once on page load. This meant that datepickers in async loaded modals never got initialized.
This PR re-executes the datepicker initializer immediately after a modal is loaded to properly register any datepickers it might have added to the dom.
Before:
After:

Managment - Re-load datepickers after modal instantiation

---

management/admin.php
management/ajax_forms.php

(issue #687 ) : Removes the IF/THEN statements from management/ajax_forms.php and management/admin.php, always displaying an "Add Category" link in the Edit Document form on the former and always displaying the Categories table in the latter. In theory this is intended behavior in the Management Module given the existing documentation.

(issue #687 ) : Unable to Create "Categories" in Management Module

---

resources/ajax_processing/submitCost.php

Newer MySQL/MariaDB versions are more strict about type restrictions, and do not like to coerce an empty string to NULL on a numeric column type.  Here we make sure that non-numeric user input is dropped, and NULL is stored when a number isn't passed to the input form.

Protect against non-numeric taxRate value

---

resources/ajax_processing/submitCost.php
resources/directory.php
resources/js/forms/externalLoginForm.js

Fixes two issues in the Resources Module:
-     The resource accounts modal had a typo stopping it from saving data properly
-     The costs table needs additional numeric normalization for both initial display and during the saving process, as was done for the taxRate field in the 2024.04 release

Fix for Resources Module 
