- reports/index.php
- reports/install/create_tables_data.sql
- reports/install/index.php
- reports/install/test_create.sql
Jeff you probably need to audit this.
> Attempt to fix Bad Merge of Reports

- usage/admin/classes/domain/SushiService.php
- usage/uploadComplete.php
- usage/uploadConfirmation.php
Previously, users were unable to import data across multiple years (it would appear as if you could, but the data would overwrite the current year's data). This pull request fixes this error, allowing users to import data across multiple years in the past, and warns the user that data will be overwritten if using SUSHI on the uploadConfirmation.php page.
> Usage module (date issue)

- licensing/templates/footer.php
- management/admin.php
- management/index.php
- management/templates/footer.php
- organizations/templates/footer.php
- resources/templates/footer.php
- usage/templates/footer.php
On thing to note is that I changed the link name from `GitHub Site` to `Coral is Free/Libre/Open Source` because when seeing GitHub site I though that Coral also had a [site hosted on GitHub](https://pages.github.com/).
If it's not appropriate just tell me and I'll change it.
> update link to source code in footer 

- auth/install/css/style.css
- indexstyle.css
- licensing/css/style.css
- management/css/style.css
- management/install/css/style.css
- organizations/css/style.css
- organizations/install/css/style.css
- resources/ajax_htmldata/getProductDetails.php
- resources/ajax_htmldata/getSearchResources.php
- resources/css/style.css
- resources/install/css/style.css
- resources/js/forms/resourceNewForm.js
- resources/js/index.js
- usage/css/style.css
- usage/install/css/style.css
> Small html, css, code style refactors and fixes

- usage/admin/classes/domain/SushiService.php
> Explicitly set the importDateTime when saving.

- resources/import.php
> Explicitly set updateDate.

- resources/js/resource.js
Fix issue #116: HTML from current tab is not duplicated anymore: id's are valid again.
> Issue #116: HTML from Ajax is duplicated 8 times (once per tab)

- resources/ajax_forms/getCostForm.php
Fix payment display when enhanced cost history is disabled
> Issue 124: Payment is missing when enhanced cost history is disabled

- index.php
I though it was responsible for some strange issue I had.
So I added it and even if had nothing to do with my problem
why not commit it.
> Index: add missing type to <script> tag

- auth/index.php
- index.php
- resources/ajax_htmldata/getSearchResources.php
- resources/directory.php
- resources/index.php
- resources/templates/footer.php
- resources/templates/header.php
- Add titles to links
- Add alt descriptions to image links
- Fix some form labels
> Accessibility (new patch)

- resources/css/style.css
- resources/js/queue.js
- resources/queue.php
This PR refactors the Queue pipeline to reduce code duplication, increase maintainability, and simplify future enhancement.
> Refactor of Queue HTML,CSS, and JS

- auth/admin.php
- licensing/templates/footer.php
- management/templates/footer.php
- organizations/templates/footer.php
- reports/templates/footer.php
- resources/templates/footer.php
- resources/templates/header.php
- templates/footer.php
- usage/templates/footer.php
This is building on the shared footer that @remocrevo started. It's basically just including it in the existing footers.
> 2.0 shared footer

- .htaccess
- admin/.htaccess
- auth/.htaccess
- licensing/.htaccess
- management/.htaccess
- organizations/.htaccess
- reports/.htaccess
- resources/.htaccess
- tests/.htaccess
- usage/.htaccess
Making htaccess files work with apache 2.4 as well as 2.2 per #158
> make htaccess apache 2.4 compatible

- licensing/templates/header.php
- management/templates/header.php
- organizations/templates/header.php
- resources/templates/header.php
- usage/templates/header.php
Addresses issue #164 by changing the links in the module headers.
> Module header help link fix

- resources/index.php
Wrapped an Html echo in a isset() IF
> Update index.php - Remove "Undefined" notice if data is missing

- resources/index.php
If there's nothing in the resourceISBNOrISSN variable, show nothing instead of a "Notice: Undefined..."
> Another IF/ELSE Statement used to remove "notice" if data is missing

- resources/install/protected/install.sql
- resources/install/protected/update_2.0.0.sql
> Error on routing screen - ResourceStep missing dateArchive

- resources/css/style.css
- resources/directory.php
- resources/js/resource.js
- resources/resource.php
This patch also remove unnecessary code which was used when image icons were still used.
Fixes Issue #34
> Rename "routing" to "workflow"

- LangCodes.php
- licensing/templates/footer.php
- management/templates/footer.php
- organizations/templates/footer.php
- reports/templates/footer.php
- resources/templates/footer.php
- templates/footer.php
- usage/templates/footer.php
Added en_GB per #49 and updated the footer for the release candidate per #199
> Release Candidate Footer

- .editorconfig
Also relates to #55, #121, & #122.
> Issue #208: add an initial .editorconfig file with some defaults.

- resources/admin/classes/domain/Resource.php
> Issue 211: Archive workflow on restart when the workflow has been marked complete

- resources/install/protected/2.0-beta-to-rc-manual.sql
Issue #215; additions based on git diff of install.sql from 2.0-beta & development branches.
> Add more to beta-to-rc sql update file.

- resources/admin/classes/common/Configuration.php
- resources/admin/classes/common/DatabaseObject.php
- resources/ajax_forms/getImportConfigForm.php
- resources/import.php
Found these when working on the resources file importer.
> Issue #77: add some checks to avoid php notices.

- resources/admin/classes/domain/Resource.php
> Display child records in alpha order

- resources/admin/classes/domain/Resource.php
- resources/admin/classes/domain/ResourceStep.php
- resources/ajax_forms/getImportConfigForm.php
- resources/import.php
- resources/js/admin.js
There were merge conflicts in PR #169 (old PR #154) that needed to be resolved. Also included are a few `isset()` calls to reduce notices in the logs.
This is the first part of the review and approval of everything in #8.
> Update PR #169 to resolve merge conflicts.

- resources/admin/classes/common/DatabaseObject.php
- resources/admin/classes/domain/ImportHistory.php
- resources/import.php
- resources/importHistory.php
- resources/install/protected/update_upload_history.sql
There were merge conflicts in PR #170 (old PR #153) that needed to be resolved. Also included an isset() call to reduce notices in the logs.
This is the second part of the review and approval of everything in #8.
> Update PR #170 to resolve merge conflicts.

- resources/admin/classes/domain/Resource.php
- resources/ajax_forms/getImportConfigForm.php
- resources/import.php
There were merge conflicts in PR #171 (old PR #152) that needed to be resolved. Also included a number of fixes to reduce warnings and notices in the logs.
This is the third part of the review and approval of everything in #8.
> Update PR #171 to resolve merge conflicts.

- organizations/admin/classes/common/DatabaseObject.php
- organizations/index.php
PHP message: PHP Notice: A session had already been started - ignoring session_start() in /var/www/coral/organizations/user.php on line 40
PHP message: PHP Notice: Undefined variable: letter in /var/www/coral/organizations/index.php on line 81
PHP message: PHP Notice: Undefined variable: letter in /var/www/coral/organizations/index.php on line 81
PHP message: PHP Notice: Undefined variable: letter in /var/www/coral/organizations/index.php on line 81
PHP message: PHP Notice: Undefined variable: letter in /var/www/coral/organizations/index.php on line 81
PHP message: PHP Notice: Undefined variable: letter in /var/www/coral/organizations/index.php on line 81
PHP message: PHP Notice: Undefined variable: letter in /var/www/coral/organizations/index.php on line 81
Issue #77
> Fix PHP Notices on organizations landing page.

- resources/install/protected/update_2.0.0.sql
> fixing typo in update script.

- resources/js/forms/workflowForm.js
> Issue 281: Fix button when adding a step in admin workflow edit

- resources/css/style.css
We've noticed that since version 2.0, content areas have been very narrow for different resource views/tabs.  This pull request is an effort to widen those areas since we're not really using a responsive design.
> Making the content areas wider for resource content areas.

- common/common_directory.php
Avoids PHP Notice: Undefined index: http_lang in common/common_directory.php on line 93.
> Issue #338: initialize 'http_lang' to NULL.

- resources/api/INSTALL
- resources/api/composer.json
- resources/api/index.php
> Use composer to manage API dependencies

- resources/ajax_processing/submitNewResource.php
- resources/api/index.php
@veggiematts 
NOTE: This commit relies on PR #345.
> fixes workflow start for new resources created by ajax form or API

- resources/ajax_forms/getCostForm.php
_("Edit Cost Information aaa"); => _("Edit Cost Information");
> Remove a test leftover in ajax_forms/getCostForm.php

- .editorconfig
Addresses #55.
See: http://cgit.drupalcode.org/drupal/tree/.editorconfig
> Issue #55: adopt the Drupal `.editorconfig` file.

- licensing/js/plugins/thickbox.js
- management/js/plugins/thickbox.js
- organizations/js/plugins/thickbox.js
- reports/js/plugins/thickbox.js
- usage/js/plugins/thickbox.js
Same fix as #391, but for the other modules.
> Allow to close a modal popup with the escape key (other modules)

- auth/css/style.css
- licensing/css/style.css
- management/css/style.css
- organizations/css/style.css
- reports/css/style.css
- resources/css/style.css
- usage/css/style.css
> Remove CSS rules for capitalization

- resources/admin/classes/domain/Resource.php
- resources/export.php
CSV export is currently broken in devel. This patch fixes it.
> Fix CSV export

- install/providers/have_default_db_user.php
This is the fix for #408.
To test, follow the same process as to replicate the issue, except the issue shouldn't occur with this change.
> Fix for #408 edge db_user check bug

- resources/import.php
This PR simply adds tabulation as a delimiter for CSV import
> Add tabulation as CSV import delimiter

- resources/directory.php
- usage/directory.php
> Issue 438: Fix resource and usage menu highlighting

- resources/js/resource.js
- resources/resource.php
Restore the accounts tab in the resource module, see Issue #439 
Alternative resolution, see PR #441
> Issue 439: Restore accounts tab

- resources/ajax_htmldata/getEbscoKbTitleDetails.php
> Fix available packages display in EBSCO KB search

- resources/admin/classes/domain/ResourceAcquisition.php
Restores PR #213 fix for Issue #211 
I enabled EditorConfig in my text editor, and it looks like it went after some of the whitespace/line endings, but the only functional change is inside the isCurrentWorkflowComplete() method.
> Restore workflow archiving fix

- usage/admin/classes/domain/SushiService.php
> Fix hard-coded dates in SushiService

- resources/ajax_htmldata/getAccessDetails.php
> Fix access edition when using icon link

- resources/ajax_htmldata/getAccountDetails.php
Issue #450 : Allow edition/deletion of local account 
(ie: not an account inherited from the organization module)
> Issue 450: Fix edition/deletion of local account 

- licensing/calendar.php
> Fix licensing calendar bad query failure

- resources/ajax_forms/getAdminUserGroupForm.php
> Issue 412: Change email address to its plural form

- resources/import.php
Do not create ResourceAcquisition, Fund, ResourcePayment, and do not try to start a workflow on import preview mode.
Basically, those things have been moved inside the resource creation "proceed" condition.
> Issue 481: Fix import preview mode.

- resources/ajax_forms/getOrderForm.php
- resources/js/forms/acquisitionsForm.js
This patch adds placeholders with date format for sub start and sub end in the orders form.
> Add placeholders for dates to orders form

- resources/ajax_processing/submitAccess.php
Issue #556.
Allows Authorized Sites to be removed.
> 556, make Authorized Sites compatible with multiple ordering

- reports/report.php
> Issue 525 report.php: typos in CSS definition

- usage/ajax_htmldata.php
> Issue 375: SUSHI server registry link

- usage/import.php
- usage/uploadConfirmation.php
> Issue 508: Misleading error message when importing

- usage/import.php
- usage/uploadConfirmation.php
- Add a specific error message when the archive directory is not writable.
> Issue 508: Misleading error message when importing usage statistics

- usage/admin/classes/domain/SushiService.php
- usage/ajax_forms.php
Fixes #480 by removing SUSHI for COUNTER 3 as this is no longer supported.
> Issue 480: SUSHI for COUNTER 3

- resources/admin/classes/common/Dashboard.php
- resources/ajax_htmldata/getDashboard.php
- resources/ajax_htmldata/getDashboardYearlyCosts.php
- resources/dashboard.php
- resources/dashboard_yearly_costs.php
- resources/js/dashboard.js
The filter by organization will include the selection of organization role (example : filter on Organization= Ebsco, role = editor)
The filter will be available to both statistics and yearly costs dashboards.
Before:
After:
Test plan:
- apply the patch
- check that you can filter by organization and role, filter by fund, group by organization, group by fund
> Dashboards: Adding the ability to limit and to group by organization and fund

- organizations/admin/classes/api_client/KohaClient.php
Test plan:
1) Add a vendor to Koha using Coral/Koha synchronization
2) Check in Koha that the vendor has been added as inactive
3) Apply the patch
4) Add another vendor to Koha using Coral/Koha synchronization
5) Check in Koha that the vendor has been added as active
> Add a vendor as active when using Coral/Koha vendors synchronization.

- resources/admin/classes/domain/Resource.php
This issue is related to some Sirsi customers experiencing long resource search load times when they have 100,000 + resources in their system. It is related to #256, but uses a much simpler fix than the one I proposed there.
As explained in #256, the root cause is the ORDER BY statement. But this can be overridden in the [configuration file](https://github.com/coral-erm/coral/blob/master/resources/admin/configuration_sample.ini#L18) by setting default sort to an empty string.
However, after doing this we still saw load times upwards of 30 seconds because the resource index page makes 2 queries per page load. One to [get the resources](https://github.com/coral-erm/coral/blob/master/resources/ajax_htmldata/getSearchResources.php#L35), and another to get the [search result …
> SirsiDynix: Improved selective joins

- resources/ajax_htmldata/getRightPanel.php
> Issue 482: Fix Resource Get Statistics button

- templates/footer.php
Change the footer back to DEVELOPMENT now that the 2020.02 release has been merged into master branch.
> Reset the footer to Development

- templates/footer.php
> release 2020.09

- organizations/ajax_forms.php
- organizations/ajax_htmldata.php
- organizations/css/style.css
- organizations/js/common.js
- organizations/js/orgDetail.js
- usage/admin/classes/domain/SushiService.php
> Fixed SUSHI Import issue

- organizations/ajax_forms.php
- organizations/ajax_htmldata.php
- organizations/css/style.css
- organizations/js/common.js
- organizations/js/orgDetail.js
> Fixed report new issue submission issue ERM-108

- organizations/ajax_forms.php
- organizations/ajax_htmldata.php
- organizations/css/style.css
- organizations/js/common.js
- organizations/js/orgDetail.js
> Fixed reporting downtime issue

- organizations/ajax_forms.php
- organizations/ajax_htmldata.php
- organizations/css/style.css
- organizations/js/common.js
- organizations/js/orgDetail.js
- usage/admin/classes/domain/SushiService.php
> Fixed blank SUSHI service modal

- licensing/onix_import.php
- usage/admin/classes/domain/SushiService.php
> Fixed ONIX-PL Import issue

- organizations/js/orgDetail.js
- resources/js/resource.js
> Fixed bugs when reporting an issue

- resources/resources/cataloging.php
- usage/admin/classes/domain/SushiService.php
> Fixed edit cataloging details issue #ERM-74

- usage/admin/classes/domain/SushiService.php
> Fixed Askews and Holts SUSHI import issue #ERM-119

- licensing/calendar.php
> Fixed characters encoding issue ERM-116

- templates/footer.php
Getting ready for release of 2024.04.
> Update version in footer for 2024.04 release.

- resources/ajax_processing/submitCost.php
- resources/directory.php
- resources/js/forms/externalLoginForm.js
This branch contains fixes for two issues in the Resources module:
* The resource accounts modal had a typo stopping it from saving data properly
* The costs table needs additional numeric normalization for both initial display and during the saving process, as was done for the taxRate field in the 2024.04 release
This branch does those things in the top two commits.
> Post-2024.04 resource fixes

- auth/install/auth.php
- install/index.php
- licensing/install/licensing.php
- management/install/management.php
- organizations/install/organizations.php
- reports/install/reports.php
- resources/install/resources.php
- templates/footer.php
- usage/install/usage.php
Updating version to 2024.10 in preparation for release.
> Updating version to 2024.10

- auth/install/auth.php
- index.php
- install/index.php
- licensing/install/licensing.php
- management/install/management.php
- organizations/install/organizations.php
- reports/install/reports.php
- resources/install/resources.php
- templates/footer.php
- usage/install/usage.php
Adds all the required version statements for Hotfix 01 of 2025.04.
> Adds Upgrade Statements for 2025.04.01

- resources/resource.php
Shifts around the check to see if a user can access the Accounts tab so that the variable $user is set before it's being checked - also changes the comparison to check for an integer of 1 rather than a string of 1.
> Resolves Issue 794

- css/style.css
- licensing/ajax_forms.php
- organizations/admin.php
- organizations/ajax_forms.php
- organizations/ajax_htmldata.php
- organizations/js/forms/issueLogSubmitForm.js
- templates/footer.php
A kind of band-aid fix for Issues 798 and 802. A lot of the submit buttons have functions attached to them that are supposed to return false (and prevent the page from loading) - in some cases, the functions just weren't being properly set due to issues here and there, but in other cases I needed to change the input from a submit to a button. I do not believe this would be the best, final solution, but it solves the immediate issue and I would recommend taking a closer look at this for a potential refactor in the future. Maybe we can add it in as part of the Resources Module release this Fall?
> Issue 798 and Issue 802 Fix

- auth/install/auth.php
- css/style.css
- index.php
- install/index.php
- licensing/install/licensing.php
- management/install/management.php
- organizations/install/organizations.php
- reports/install/reports.php
- resources/admin/classes/domain/Resource.php
- resources/ajax_htmldata/getSearchResources.php
- resources/install/resources.php
- templates/footer.php
- usage/install/usage.php
* Issue 625 - Helps visually distinguish archived resources by italicizing the name of the resource. 
* Issue 659 - Corrects an issue with the export by correcting some of the column aliases to match.
> CORAL v2025.04.04

- auth/install/auth.php
- css/style.css
- index.php
- install/index.php
- licensing/install/licensing.php
- management/install/management.php
- organizations/install/organizations.php
- reports/install/reports.php
- resources/admin/classes/domain/Resource.php
- resources/ajax_htmldata/getSearchResources.php
- resources/install/resources.php
- templates/footer.php
- usage/install/usage.php
Merges Hotfix 2025.04.04 into the main branch
> v2025.04.04

- auth/install/auth.php
- css/style.css
- index.php
- install/index.php
- licensing/install/licensing.php
- management/install/management.php
- organizations/install/organizations.php
- reports/install/reports.php
- resources/admin/classes/domain/UserGroup.php
- resources/ajax_forms/getAdminUserGroupForm.php
- resources/ajax_htmldata/getProductDetails.php
- resources/ajax_processing/submitUserGroup.php
- resources/install/resources.php
- resources/js/forms/userGroupForm.js
- templates/footer.php
- usage/index.php
- usage/install/usage.php
- usage/js/index.js
* Update getProductDetails.php
Removes Resource Note ID to resolve Issue 817.
* Adds Toggleable Notice to Usage Stats Main Page
Adds a toggleable notice to the main page of the Usage Stats module, letting folks know that development is seeking volunteers. Also styles the page and sets up javascript for the toggle button.
* Half Resolves Workflow Issue
Updates adding and removing members of a group in the workflow tab. Half resolves Issue 771 (which also identified an issue with the Workflow Steps form).
* 2024.04.05 Updates
Updates the installer for v2024.04.05.
> V2025.04.05 (#822)

- auth/admin/classes/common/Utility.php
- licensing/admin/classes/common/Utility.php
- management/admin/classes/common/Utility.php
- organizations/admin/classes/common/Utility.php
- reports/admin/classes/common/Utility.php
- resources/admin/classes/common/Utility.php
- resources/admin/classes/domain/Workflow.php
- resources/ajax_forms/getAdminWorkflowForm.php
- resources/ajax_processing/submitWorkflow.php
- resources/js/forms/workflowForm.js
- usage/admin/classes/common/Utility.php
* [Issue 771](https://github.com/coral-erm/coral/issues/771) - Finishes resolution of Issue 771, Refactors the Admin area workflow code to more easily add, remove, and edit workflow steps. Adds in a validation check to confirm that circular logic cannot be applied to workflow steps via the parents of the step. Fixes the display order to match both the form and the workflow when it is in a resources screen.
* [Issue 824](https://github.com/coral-erm/coral/issues/824) - Resolves issue where emails were unable to send due to the updated pathing method not having a forward slash at the end.
> V2025.04.06
